language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

before_script: yarn test

jobs:
  include:
    - stage: build
      name: "test"
      if: branch = develop
      script: yarn build
      env:
        - RIDI_PAY_HOST=pay.ridi.io
        - RIDI_PAY_API_SERVER_HOST=pay-api.dev.ridi.io
        - RIDIBOOKS_HOST=master.test.ridi.io
        - ACCOUNT_SERVER_HOST=account.dev.ridi.io
        - OAUTH2_CLIENT_ID=${DEV_OAUTH2_CLIENT_ID}
        - S3_BUCKET_NAME=ridi-pay-frontend-test
    -
      name: "staging"
      if: branch = master
      script: yarn build
      env:
        - RIDI_PAY_HOST=staging.pay.ridibooks.com
        - RIDI_PAY_API_SERVER_HOST=staging.pay-api.ridibooks.com
        - RIDIBOOKS_HOST=ridibooks.com
        - ACCOUNT_SERVER_HOST=account.ridibooks.com
        - OAUTH2_CLIENT_ID=${PROD_OAUTH2_CLIENT_ID}
        - S3_BUCKET_NAME=ridi-pay-frontend-staging
    -
      name: "prod"
      if: tag IS present
      script: yarn build
      env:
        - RIDI_PAY_HOST=pay.ridibooks.com
        - RIDI_PAY_API_SERVER_HOST=pay-api.ridibooks.com
        - RIDIBOOKS_HOST=ridibooks.com
        - ACCOUNT_SERVER_HOST=account.ridibooks.com
        - OAUTH2_CLIENT_ID=${PROD_OAUTH2_CLIENT_ID}
        - S3_BUCKET_NAME=ridi-pay-frontend-prod

deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: ${S3_BUCKET_NAME}
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: dist
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|develop$ || -n $TRAVIS_TAG
