language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

before_script: yarn test

jobs:
  include:
    - stage: build
      name: "test"
      if: branch = develop
      script: yarn build
      env:
        - RIDI_PAY_HOST=pay.ridi.io
        - RIDI_PAY_API_SERVER_HOST=api.pay.ridi.io
        - RIDIBOOKS_HOST=dev.ridi.io
        - ACCOUNT_SERVER_HOST=account.dev.ridi.io
        - OAUTH2_CLIENT_ID=${DEV_OAUTH2_CLIENT_ID}
    -
      name: "staging"
      if: branch = master
      script: yarn build
      env:
        - RIDI_PAY_HOST=staging.pay.ridibooks.com
        - RIDI_PAY_API_SERVER_HOST=api.staging.pay.ridibooks.com
        - RIDIBOOKS_HOST=ridibooks.com
        - ACCOUNT_SERVER_HOST=account.ridibooks.com
        - OAUTH2_CLIENT_ID=${PROD_OAUTH2_CLIENT_ID}
    -
      name: "prod"
      if: branch = master AND tag = true
      script: yarn build
      env:
        - RIDI_PAY_HOST=pay.ridibooks.com
        - RIDI_PAY_API_SERVER_HOST=api.pay.ridibooks.com
        - RIDIBOOKS_HOST=ridibooks.com
        - ACCOUNT_SERVER_HOST=account.ridibooks.com
        - OAUTH2_CLIENT_ID=${PROD_OAUTH2_CLIENT_ID}

deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: ridi-pay-frontend-prod
    region: ap-northeast-2
    local_dir: dist
    on:
      branch: master
      tags: true

  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: ridi-pay-frontend-staging
    region: ap-northeast-2
    local_dir: dist
    on:
      branch: master

  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: ridi-pay-frontend-test
    region: ap-northeast-2
    local_dir: dist
    on:
      branch: develop