language: node_js
node_js:
  - "8"
cache: yarn

stages:
  - test
  - build

jobs:
  include:
    - stage: build
      name: "test"
      if: branch = develop
      script: yarn build
      env:
        - RIDI_PAY_API_SERVER_HOST=api.pay.ridi.io
        - RIDIBOOKS_HOST=dev.ridi.io
    -
      name: "staging"
      if: branch = master
      script: yarn build
      env:
        - RIDI_PAY_API_SERVER_HOST=api.staging.pay.ridibooks.com
        - RIDIBOOKS_HOST=ridibooks.com
    -
      name: "prod"
      if: branch = master AND tag = true
      script: yarn build
      env:
        - RIDI_PAY_API_SERVER_HOST=api.pay.ridibooks.com
        - RIDIBOOKS_HOST=ridibooks.com
        - ACCOUNT_SERVER_HOST=account.ridibooks.com
        - OAUTH2_CLIENT_ID=$PROD_OAUTH2_CLIENT_ID

deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: ridi-pay-frontend-prod
    skip_cleanup: true
    local_dir: dist
    on:
      branch: master
      tags: true

  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: ridi-pay-frontend-staging
    local_dir: dist
    on:
      branch: master

  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: ridi-pay-frontend-test
    local_dir: dist
    on:
      branch: develop