export * from './AddCard';
export * from './Error404';
export * from './Payment';
export * from './SetOnetouch';
export * from './SetPin';
export * from './Settings';
export * from './Terms';
export * from './ValidatePassword';
export * from './ValidatePin';
